#!/bin/sh

set -eu

echo "> POST INSTALL HOOK"

USER="automac"

echo "> Set the primary language for the system"

languagesetup -langspec en

echo "> Creating user $USER"

dscl . -create "/Users/$USER"
dscl . -create "/Users/$USER" UserShell /bin/bash
dscl . -create "/Users/$USER" RealName "Automac"
dscl . -create "/Users/$USER" UniqueID 503
dscl . -create "/Users/$USER" PrimaryGroupID 503
dscl . -create "/Users/$USER" NFSHomeDirectory "/Local/Users/$USER"
dscl . -passwd "/Users/$USER" "$USER"
dscl . -append /Groups/admin GroupMembership "$USER"
